export const colors = {
  primary: '#7C4DFF',
  primaryDark: '#6F00FF',
  primarySoft: '#EEE9FF',
  ink: '#1E1E22',
  canvas: '#FFFFFF',
  surface: '#FFFFFF',
  surfaceWarm: '#F3F6FB',
  stage: '#E1E6EE',
  hairline: '#F1F2F6',
  border: '#CFCFE2',
  borderStrong: '#9C9BC2',
  muted: '#9C9BC2',
  mutedStrong: '#81809E',
  bodySecondary: '#81809E',
  disabledBg: '#E1E6EE',
  disabledText: '#9C9BC2',
  selectedSoft: '#F3F6FB',
  recovery: '#7C4DFF',
  recoverySoft: '#EEE9FF',
  performance: '#7C4DFF',
  performanceSoft: '#EEE9FF',
  danger: '#E5484D',
  success: '#2DBE7F',
  white: '#FFFFFF',
  background: '#FFFFFF',
  parchment: '#FFFFFF',
  ceramic: '#E1E6EE',
  surfaceCool: '#F3F6FB',
  surfaceDark: '#1E1E22',
  surfaceDark2: '#33384B',
  surfaceIron: '#1E1E22',
  surfaceIronSoft: '#33384B',
  textPrimary: '#1E1E22',
  textSecondary: '#9C9BC2',
  textOnDark: '#FFFFFF',
  mutedOnDark: 'rgba(255, 255, 255, 0.76)',
  accent: '#7C4DFF',
  accentFocus: '#6F00FF',
  accentOnDark: '#FFFFFF',
  accentLight: '#EEE9FF',
  houseGreen: '#7C4DFF',
  upliftGreen: '#6F00FF',
  gold: '#7C4DFF',
  goldLight: '#CFCFE2',
  goldLightest: '#F3F6FB',
  blue: '#7C4DFF',
  chip: '#F3F6FB',
};

export const spacing = { micro: 4, xs: 8, sm: 12, md: 16, lg: 20, screen: 24, xl: 32, xxl: 48 };

export const radius = { subtle: 4, control: 12, card: 16, chip: 32, avatar: 999 };

export const componentSizes = {
  primaryButtonHeight: 56,
  secondaryButtonHeight: 56,
  searchHeight: 56,
  tabBarHeight: 80,
  floatingActionSize: 56,
};

export const motion = {
  pressDuration: '120ms',
  stateDuration: 180,
  pressScale: 0.97,
  easeOut: [0.23, 1, 0.32, 1],
};

export const typography = {
  heroDisplay: { fontFamily: 'Overpass_800ExtraBold', fontSize: 32, lineHeight: 42 },
  displayLarge: { fontFamily: 'Overpass_700Bold', fontSize: 24, lineHeight: 31 },
  lead: { fontFamily: 'Overpass_400Regular', fontSize: 16, lineHeight: 24 },
  statNumber: { fontFamily: 'Overpass_700Bold', fontSize: 32, lineHeight: 42 },
  statLabel: { fontFamily: 'Overpass_600SemiBold', fontSize: 12, lineHeight: 17, color: colors.muted },
  screenTitle: { fontFamily: 'Overpass_700Bold', fontSize: 24, lineHeight: 31 },
  cardTitle: { fontFamily: 'Overpass_600SemiBold', fontSize: 16, lineHeight: 24 },
  body: { fontFamily: 'Overpass_400Regular', fontSize: 16, lineHeight: 24 },
  caption: { fontFamily: 'Overpass_400Regular', fontSize: 14, lineHeight: 21 },
  action: { fontFamily: 'Overpass_700Bold', fontSize: 16, lineHeight: 24 },
  metaSmall: { fontFamily: 'Overpass_600SemiBold', fontSize: 12, lineHeight: 17 },
};
